CREATE TABLE `actors` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`actor_name` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=6